apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yasser
  name: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yasser
  template:
    metadata:
      labels:
        app: yasser
    spec:
      containers:
      - image: yasseralhwetat/orange-httpd:omar
        name: python
