apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python
  name: python
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - image: httpd
        name: python
